<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260913090000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace task hierarchy with simple checklist items; preserve titles, completion, descriptions and files.';
    }

    public function up(Schema $schema): void
    {
        // Preserve rich legacy content in the task, but never silently exceed the form's limit.
        $tooLong = $this->connection->fetchOne(<<<'SQL'
SELECT COUNT(*) FROM task t JOIN (
    SELECT parent_id, string_agg(title || E'\n' || description, E'\n\n' ORDER BY created_at, id) AS notes
    FROM task WHERE parent_id IS NOT NULL AND description <> '' GROUP BY parent_id
) old_notes ON t.id = old_notes.parent_id
WHERE length(t.description || E'\n\n' || old_notes.notes) > 50000
SQL);
        $this->abortIf((int) $tooLong > 0, 'Combining legacy descriptions would exceed 50000 characters. Shorten or export them before migrating.');
        $this->addSql('CREATE TABLE checklist_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, task_id INT NOT NULL, title VARCHAR(200) NOT NULL, completed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_checklist_task ON checklist_item (task_id)');
        $this->addSql('ALTER TABLE checklist_item ADD CONSTRAINT fk_checklist_task FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE');
        $this->addSql("ALTER TABLE checklist_item ADD CONSTRAINT checklist_title_not_blank CHECK (length(btrim(title)) > 0)");
        $this->addSql('INSERT INTO checklist_item (task_id, title, completed, created_at) SELECT parent_id, title, completed, created_at FROM task WHERE parent_id IS NOT NULL ORDER BY created_at, id');
        $this->addSql(<<<'SQL'
UPDATE task t SET description = CASE WHEN t.description = '' THEN old_notes.notes ELSE t.description || E'\n\n' || old_notes.notes END
FROM (
    SELECT parent_id, string_agg(title || E'\n' || description, E'\n\n' ORDER BY created_at, id) AS notes
    FROM task WHERE parent_id IS NOT NULL AND description <> '' GROUP BY parent_id
) old_notes WHERE t.id = old_notes.parent_id
SQL);
        $this->addSql('UPDATE attachment a SET task_id = t.parent_id FROM task t WHERE a.task_id = t.id AND t.parent_id IS NOT NULL');
        // Do not repoint legacy links: that would grant access to a larger task than originally shared.
        $this->addSql('DELETE FROM task_share_link s USING task t WHERE s.task_id = t.id AND t.parent_id IS NOT NULL');
        $this->addSql('DELETE FROM task WHERE parent_id IS NOT NULL');
        $this->addSql('DROP TRIGGER validate_task_links ON task');
        $this->addSql('DROP FUNCTION validate_task_links()');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT root_task_priority');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT child_has_no_block');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT task_not_own_parent');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25727ACA70');
        $this->addSql('DROP INDEX IDX_527EDB25727ACA70');
        $this->addSql('ALTER TABLE task DROP parent_id');
        $this->addSql('ALTER TABLE task ALTER priority SET NOT NULL');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT task_priority_nonnegative CHECK (priority >= 0)');
        $this->addSql(<<<'SQL'
CREATE FUNCTION validate_task_links() RETURNS trigger AS $$
DECLARE block_owner int;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.owner_id IS DISTINCT FROM OLD.owner_id THEN
            RAISE EXCEPTION 'Task owner is immutable' USING ERRCODE = '23514';
        END IF;
    END IF;
    IF NEW.block_id IS NOT NULL THEN
        SELECT owner_id INTO block_owner FROM task_block WHERE id = NEW.block_id FOR KEY SHARE;
        IF NOT FOUND OR block_owner <> NEW.owner_id THEN
            RAISE EXCEPTION 'Task block must have the same owner' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql
SQL);
        $this->addSql('CREATE TRIGGER validate_task_links BEFORE INSERT OR UPDATE ON task FOR EACH ROW EXECUTE FUNCTION validate_task_links()');
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException('Restore a database backup to recover the previous task hierarchy and legacy links.');
    }
}
