<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260912134243 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create users, task blocks, tasks, attachments, share links and the file deletion queue.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform, 'PostgreSQL is required.');
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE attachment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_name VARCHAR(255) NOT NULL, stored_name VARCHAR(64) NOT NULL, mime_type VARCHAR(127) NOT NULL, size INT NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, task_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_795FD9BB1185AF6A ON attachment (stored_name)');
        $this->addSql('CREATE INDEX IDX_795FD9BB8DB60186 ON attachment (task_id)');
        $this->addSql('CREATE TABLE pending_file_deletion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stored_name VARCHAR(64) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4E1C81E71185AF6A ON pending_file_deletion (stored_name)');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, description TEXT NOT NULL, completed BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, owner_id INT NOT NULL, parent_id INT DEFAULT NULL, block_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB257E3C61F9 ON task (owner_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25727ACA70 ON task (parent_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25E9ED820C ON task (block_id)');
        $this->addSql('CREATE TABLE task_block (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_44BF8C027E3C61F9 ON task_block (owner_id)');
        $this->addSql('CREATE TABLE task_share_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, task_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9778DFC7B3BC57DA ON task_share_link (token_hash)');
        $this->addSql('CREATE INDEX IDX_9778DFC78DB60186 ON task_share_link (task_id)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BB8DB60186 FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB257E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25727ACA70 FOREIGN KEY (parent_id) REFERENCES task (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25E9ED820C FOREIGN KEY (block_id) REFERENCES task_block (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_block ADD CONSTRAINT FK_44BF8C027E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_share_link ADD CONSTRAINT FK_9778DFC78DB60186 FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE attachment DROP CONSTRAINT FK_795FD9BB8DB60186');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB257E3C61F9');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25727ACA70');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25E9ED820C');
        $this->addSql('ALTER TABLE task_block DROP CONSTRAINT FK_44BF8C027E3C61F9');
        $this->addSql('ALTER TABLE task_share_link DROP CONSTRAINT FK_9778DFC78DB60186');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE attachment');
        $this->addSql('DROP TABLE pending_file_deletion');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE task_block');
        $this->addSql('DROP TABLE task_share_link');
    }
}
